<?php

/**
 * @file
 * Install, update and uninstall functions for the Ban module.
 */

/**
 * Implements hook_schema().
 */
function ban_schema()
  $schema['ban_ip'] = [
    'description' => 'Stores banned IP addresses.',
    'fields' => [
      'iid' => [

        'description' => 'IP address',
        'type' => 'varchar_ascii',
        'length' => 40,
        'not null' => TRUE,
        'default' => '',
      ],\],
    'primary key' => ['iid'],
  ];
  return $schema;
}
